Controllers/AlgorithmController.cs
using AuctionApplication.Models;
using AuctionApplication.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AuctionApplication.Controllers
{
    public class AlgorithmController : Controller
    {
        public IActionResult Index(AlgorithmModel algorithmModel)
        {
            int userId = (int)TempData["userId"];
            TempData.Keep("userId");
            List<(int ItemId, string ItemName, double Result)> finalResult;
            finalResult = algorithmModel.GetBestAuction(userId);
            algorithmModel.Scalarization(userId);
            ViewData["result"] = finalResult;
            return View();
        }

        public IActionResult Main()
        {
            return RedirectToAction("Index", "Main");
        }
    }
}

Views/Algorithm/Index.cshtml
@model IEnumerable<AuctionApplication.Models.AlgorithmModel>


<h4>List of criterions</h4>
<hr />

<form asp-controller="Algorithm" asp-action="Index">
    <table class="table">
        <thead>
            <tr>
                <th>
                    Criterion description
                </th>
                <th>
                    Set rating
                </th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    Duration of auction
                </td>
                <td>
                    <fieldset>
                        Change rating: <select id="DurationOfAuctionRating" name="DurationOfAuctionRating">
                            <option value="0.1">Very low</option>
                            <option value="0.25">Low</option>
                            <option value="0.5">Slightly low</option>
                            <option selected="selected" value="1">Medium</option>
                            <option value="2">Slightly high</option>
                            <option value="4">High</option>
                            <option value="10">Very high</option>
                        </select>
                    </fieldset>
                </td>
            </tr>
            <tr>
                <td>
                    Frequency of the items
                </td>
                <td>
                    <fieldset>
                        Change rating: <select id="FrequencyOfTheItemsRating" name="FrequencyOfTheItemsRating">
                            <option value="0.1">Very low</option>
                            <option value="0.25">Low</option>
                            <option value="0.5">Slightly low</option>
                            <option selected="selected" value="1">Medium</option>
                            <option value="2">Slightly high</option>
                            <option value="4">High</option>
                            <option value="10">Very high</option>
                        </select>
                    </fieldset>
                </td>
            </tr>
            <tr>
                <td>
                    Average price
                </td>
                <td>
                    <fieldset>
                        Change rating: <select id="AveragePriceRating" name="AveragePriceRating">
                            <option value="0.1">Very low</option>
                            <option value="0.25">Low</option>
                            <option value="0.5">Slightly low</option>
                            <option selected="selected" value="1">Medium</option>
                            <option value="2">Slightly high</option>
                            <option value="4">High</option>
                            <option value="10">Very high</option>
                        </select>
                    </fieldset>
                </td>
            </tr>
            <tr>
                <td>
                    Rating of categories
                </td>
                <td>
                    <fieldset>
                        Change rating: <select id="RatingOfCategoriesRating" name="RatingOfCategoriesRating">
                            <option value="0.1">Very low</option>
                            <option value="0.25">Low</option>
                            <option value="0.5">Slightly low</option>
                            <option selected="selected" value="1">Medium</option>
                            <option value="2">Slightly high</option>
                            <option value="4">High</option>
                            <option value="10">Very high</option>
                        </select>
                    </fieldset>
                </td>
            </tr>
            <tr>
                <td>
                    Rating of items
                </td>
                <td>
                    <fieldset>
                        Change rating: <select id="RatingOfItemsRating" name="RatingOfItemsRating">
                            <option value="0.1">Very low</option>
                            <option value="0.25">Low</option>
                            <option value="0.5">Slightly low</option>
                            <option selected="selected" value="1">Medium</option>
                            <option value="2">Slightly high</option>
                            <option value="4">High</option>
                            <option value="10">Very high</option>
                        </select>
                    </fieldset>
                </td>
            </tr>
        </tbody>
    </table>
    <div class="form-group" style="margin-top:30px">
        <input type="submit" value="Submit" class="btn btn-secondary" />
    </div>
</form>

<hr/>

<h6 style="margin-top:30px">List of items ordered in the best way according to user preferences:</h6>
<table class="table">
    <thead>
        <tr>
            <th>
                Item
            </th>
            <th>
                Result
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var pref in (List<(int ItemId, string ItemName, double Result)>)ViewData["result"])
        {
            <tr>
                <td>
                    @pref.ItemName
                </td>
                <td>
                    @pref.Result
                </td>
            </tr>
        }
    </tbody>
</table>

<div class="row" style="margin-top:30px">
    <div class="col-md-4">
        <form asp-action="Main">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input type="submit" value="Go back to the main view" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>